const table = [
    {
      id: 1,
      Name: 'Tiger Nixon',
      LastName: 'Nixon',
      Title: 'N/A',
      Email: 'TigerNixon@gmail.com',
      Company: 'N/A',
      Position: 'System Architect',
      Office: 'Edinburgh',
      Leads: 'N/A',
      StartDate: '2011-04-25',
    },
    {
      id: 2,
      Name: 'Garrett Winters',
      LastName: 'Winters',
      Title: 'N/A',
      Email: 'GarrettWinters@gmail.com',
      Company: 'N/A',
      Position: 'Accountant',
      Office: 'Tokyo',
      Leads: 'N/A',
      StartDate: '2011-07-25',
    },
    {
      id: 3,
      Name: 'Ashton Cox',
      LastName: 'Cox',
      Title: 'N/A',
      Email: 'Vaneet.Gupta@ezuka.com',
      Company: 'N/A',
      Position: 'Junior Technical Author',
      Office: 'San Francisco',
      Leads: 'N/A',
      StartDate: '2009-01-12',
    },
    {
      id: 4,
      Name: 'Cedric Kelly',
      LastName: 'Kelly',
      Title: 'N/A',
      Email: 'test12345@testing.mail.com',
      Company: 'N/A',
      Position: 'Senior Javascript Developer',
      Office: 'San Francisco',
      Leads: 'N/A',
      StartDate: '2012-03-29',
    },
    {
      id: 5,
      Name: 'Airi Satou',
      LastName: 'Satou',
      Title: 'N/A',
      Email: 'AiriSatou@testing.mail.com',
      Company: 'N/A',
      Position: 'Accountant',
      Office: 'Tokyo',
      Leads: 'N/A',
      StartDate: '2008-11-28',
    },
    {
    id: 6,
      Name: 'Tiger Nixon',
      LastName: 'Nixon',
      Title: 'N/A',
      Email: 'TigerNixon@gmail.com',
      Company: 'N/A',
      Position: 'System Architect',
      Office: 'Edinburgh',
      Leads: 'N/A',
      StartDate: '2011-04-25',
    },
    {
      id: 7,
      Name: 'Garrett Winters',
      LastName: 'Winters',
      Title: 'N/A',
      Email: 'GarrettWinters@gmail.com',
      Company: 'N/A',
      Position: 'Accountant',
      Office: 'Tokyo',
      Leads: 'N/A',
      StartDate: '2011-07-25',
    },
    {
      id: 8,
      Name: 'Ashton Cox',
      LastName: 'Cox',
      Title: 'N/A',
      Email: 'Vaneet.Gupta@ezuka.com',
      Company: 'N/A',
      Position: 'Junior Technical Author',
      Office: 'San Francisco',
      Leads: 'N/A',
      StartDate: '2009-01-12',
    },
    {
      id: 9,
      Name: 'Cedric Kelly',
      LastName: 'Kelly',
      Title: 'N/A',
      Email: 'test12345@testing.mail.com',
      Company: 'N/A',
      Position: 'Senior Javascript Developer',
      Office: 'San Francisco',
      Leads: 'N/A',
      StartDate: '2012-03-29',
    },
    {
      id: 10,
      Name: 'Airi Satou',
      LastName: 'Satou',
      Title: 'N/A',
      Email: 'AiriSatou@testing.mail.com',
      Company: 'N/A',
      Position: 'Accountant',
      Office: 'Tokyo',
      Leads: 'N/A',
      StartDate: '2008-11-28',
    },
    {
    id: 11,
      Name: 'Tiger Nixon',
      LastName: 'Nixon',
      Title: 'N/A',
      Email: 'TigerNixon@gmail.com',
      Company: 'N/A',
      Position: 'System Architect',
      Office: 'Edinburgh',
      Leads: 'N/A',
      StartDate: '2011-04-25',
    },
    {
      id: 12,
      Name: 'Garrett Winters',
      LastName: 'Winters',
      Title: 'N/A',
      Email: 'GarrettWinters@gmail.com',
      Company: 'N/A',
      Position: 'Accountant',
      Office: 'Tokyo',
      Leads: 'N/A',
      StartDate: '2011-07-25',
    },
    {
      id: 13,
      Name: 'Ashton Cox',
      LastName: 'Cox',
      Title: 'N/A',
      Email: 'Vaneet.Gupta@ezuka.com',
      Company: 'N/A',
      Position: 'Junior Technical Author',
      Office: 'San Francisco',
      Leads: 'N/A',
      StartDate: '2009-01-12',
    },
    {
      id: 14,
      Name: 'Cedric Kelly',
      LastName: 'Kelly',
      Title: 'N/A',
      Email: 'test12345@testing.mail.com',
      Company: 'N/A',
      Position: 'Senior Javascript Developer',
      Office: 'San Francisco',
      Leads: 'N/A',
      StartDate: '2012-03-29',
    },
    {
      id: 15,
      Name: 'Airi Satou',
      LastName: 'Satou',
      Title: 'N/A',
      Email: 'AiriSatou@testing.mail.com',
      Company: 'N/A',
      Position: 'Accountant',
      Office: 'Tokyo',
      Leads: 'N/A',
      StartDate: '2008-11-28',
    },
  ]
  export default table;